# Generated by Django 6.0.2 on 2026-02-05 11:51

import django.db.models.deletion
import registry.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('record_type', models.CharField(choices=[('certificate', 'Certificate'), ('license', 'License'), ('permit', 'Permit'), ('other', 'Other')], db_index=True, default='certificate', max_length=30)),
                ('category', models.CharField(choices=[('quality', 'Quality'), ('hse', 'HSE / Safety'), ('environment', 'Environment'), ('compliance', 'Compliance'), ('vendor', 'Vendor'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('renewed', 'Renewed'), ('archived', 'Archived')], db_index=True, default='active', max_length=30)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('site_location', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=registry.models.attachment_upload_to)),
                ('file_type', models.CharField(choices=[('certificate_copy', 'Certificate Copy'), ('renewal_document', 'Renewal Document'), ('evidence', 'Evidence'), ('communication', 'Communication'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='registry.record')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('renewed', 'Renewed'), ('status_changed', 'Status Changed'), ('comment', 'Comment')], db_index=True, max_length=30)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='registry.record')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['organization', 'status', 'expiry_date'], name='registry_re_organiz_ca2689_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['organization', 'category', 'expiry_date'], name='registry_re_organiz_fad4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['organization', 'record_type', 'expiry_date'], name='registry_re_organiz_c473db_idx'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', False)), name='record_expiry_required'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['record', 'file_type'], name='registry_at_record__3f4948_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['record', 'version'], name='registry_at_record__fc7064_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['record', 'action', 'created_at'], name='registry_ac_record__e03e0a_idx'),
        ),
    ]
