# Generated by Django 6.0.2 on 2026-02-05 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('applies_to_all', models.BooleanField(db_index=True, default=True)),
                ('record_type', models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('license', 'License'), ('permit', 'Permit'), ('other', 'Other')], db_index=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, choices=[('quality', 'Quality'), ('hse', 'HSE / Safety'), ('environment', 'Environment'), ('compliance', 'Compliance'), ('vendor', 'Vendor'), ('other', 'Other')], db_index=True, max_length=30, null=True)),
                ('offsets_days', models.JSONField(blank=True, default=list)),
                ('escalate_enabled', models.BooleanField(default=True)),
                ('escalate_offsets_days', models.JSONField(blank=True, default=list)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('teams', 'Microsoft Teams (Future)'), ('other', 'Other')], default='email', max_length=20)),
                ('email_subject_template', models.CharField(blank=True, max_length=200)),
                ('email_body_template', models.TextField(blank=True)),
                ('escalation_recipients', models.ManyToManyField(blank=True, help_text='Users to receive escalations (e.g., managers/compliance).', related_name='escalation_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_rules', to='accounts.organization')),
            ],
            options={
                'ordering': ['-enabled', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('reminder', 'Reminder'), ('escalation', 'Escalation')], db_index=True, default='reminder', max_length=20)),
                ('trigger_date', models.DateField(db_index=True, help_text='The date this notification was due to run.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('payload_summary', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='accounts.organization')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='registry.record')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='notifications.notificationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['organization', 'enabled'], name='notificatio_organiz_9c1061_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['organization', 'applies_to_all'], name='notificatio_organiz_dc46c6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrule',
            index=models.Index(fields=['organization', 'record_type', 'category'], name='notificatio_organiz_2d1fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['organization', 'status', 'trigger_date'], name='notificatio_organiz_a68034_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['record', 'kind', 'trigger_date'], name='notificatio_record__0b4135_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('record', 'rule', 'kind', 'trigger_date'), name='uniq_notification_per_record_rule_kind_triggerdate'),
        ),
    ]
